# Generated by Django 4.1.7 on 2023-03-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBCONN', '0003_employeedetails_villa_ismetro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menu', models.CharField(max_length=50)),
                ('noOfTable', models.IntegerField(max_length=8)),
                ('section', models.CharField(max_length=5)),
                ('price', models.FloatField(max_length=4)),
            ],
        ),
    ]
